### PR TITLE
Upgrade mocha to 8.x.x release

### PR DESCRIPTION
**Pull request by jayaddison**
This change upgrades the [`mocha`](https://github.com/mochajs/mocha) dependency for `js-delta-crdts-msgpack-codec` to include a security fix (see the [release details](https://github.com/mochajs/mocha/releases/tag/v7.1.1)). 

The mocha project will [not be backporting](https://github.com/mochajs/mocha/pull/4224) this fix to `mocha@5.x.x`.

~~This change also commits the NPM `package-lock.json`, since it is [intended to be committed](https://docs.npmjs.com/configuring-npm/package-lock-json.html) to source repositories.~~  From viewing other projects, practices seem to differ here, so I've reverted this change.

NB: The `^7.1.2` version specification does not pin to `7.1.2` specifically; the caret (`^`) symbol only matches against the left-most digit when checking for upgrades.  I figure it's useful to specify the full three-digit version that was most-recent at the time of writing.

cc @pgte

### CODE REVIEW

**Comment by jayaddison** [comment]
@pgte Might we be able to merge this upgrade?  It's not a hugely exciting update but it does remove a bit of `npm audit` noise, and reduces the dependency set a little.

**Comment by pgte** [comment]
@jayaddison I no longer can maintain these packages. Perhaps @jimpick can or knows who can?

**Comment by jayaddison** [comment]
Let me know if there's anything else that could help for merge-readiness here @jimpick; I've updated the pull request to upgrade to mocha 8.x.x since that major version's now available; the largest change per their [release notes](https://github.com/mochajs/mocha/blob/v8.0.0/CHANGELOG.md) is that NodeJS 10+ is required.

**Comment by jayaddison** [comment]
cc @jimpick - this is a small version bump (and dependency re-arrangement) for `js-delta-crdts-msgpack-codec` to reduce a bit of NPM audit noise and minimize imported (non-dev)dependencies.

**Comment by jayaddison** [comment]
Closing as stale.

**Pull request closed without merging**
